### ISSUE TITLE
SummOfInt

### ISSUE THREAD

**Issue by milkina** [musicsupermax/Homeworks#1]
1. Вызывайте hasNextInt перед каждым nextInt.
2. Вынести в отд. метод операции по вводу чисел. На уроке разбирали.

**Comment by musicsupermax** [comment]
Исправил

**Comment by milkina** [comment]
1. Сканнер вынесите в метод main и передавайте в качестве параметра в метод inputValue.
2.  Вместо
int i = sc.nextInt();
        return i;
лучше

return  sc.nextInt();

**Comment by musicsupermax** [comment]
Переделал

**Comment by musicsupermax** [comment]
Сделал
