### ISSUE TITLE
SmallestModule

### ISSUE THREAD

**Issue by milkina** [musicsupermax/Homeworks#2]
1.Вызывайте hasNextInt перед каждым nextInt.
2.Вынести в отд. метод операции по вводу чисел. На уроке разбирали.
3. Неотформатировано

**Comment by musicsupermax** [comment]
Исправил

**Comment by milkina** [comment]
Сканнер вынесите в метод main и передавайте в качестве параметра в метод inputValue.

**Comment by musicsupermax** [comment]
Переделал
