### ISSUE TITLE
ArrayBubbleSort

### ISSUE THREAD

**Issue by milkina** [musicsupermax/Homeworks#3]
1.  sortChangedB. 
Лучше так - for (int j = 0; j < array.length - 1-i;
2. Вместо  if (b == false)  лучше  if (!b )

**Comment by musicsupermax** [comment]
если делать if (!b) досрочная сортировка не будет выполняться

**Comment by milkina** [comment]
if (b == false)  эквивалентено  if (!b ).

**Comment by musicsupermax** [comment]
да, всё работает, исправил
