### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by milkina** [musicsupermax/Homeworks#6]
1.  На вход методов sum, mult передавайте объект класса Matrix.
2. Инициализируйте переменные  int lines;    int columns; в конструкторе.
3. Пусть методы работают с матрицами разной размерности , не только 2x3.
4. Пусть методы возвращают объект содержащий новую матрицу. Распечатывайте содержимое в методе main. Методы лучше проектировать так, чтобы они выполняли только одно действие.
5.  Умножение матриц - Две матрицы можно перемножить между собой тогда и только тогда, когда количество столбцов первой матрицы равно количеству строк второй матрицы.

 Результатом умножения матриц Am×n и Bn×k будет матрица Cm×k такая, что элемент матрицы C, стоящий в i-той строке и j-том столбце (cij), равен сумме произведений элементов i-той строки матрицы A на соответствующие элементы j-того столбца матрицы B:
cij = ai1 · b1j + ai2 · b2j + ... + ain · bnj

**Comment by musicsupermax** [comment]
Исправил + добавил 8 и 9 уроки

**Comment by musicsupermax** [comment]
добавил также 10 урок
