### ISSUE TITLE
Одежда

### ISSUE THREAD

**Issue by milkina** [musicsupermax/Homeworks#8]
1. Класс Clothing просила сделать абстрактным. 
2. Добавьте методы equals
3. Вместо   if (clothing1 instanceof Tshirt || clothing1 instanceof Trousers
                    || clothing1 instanceof Tie)
можно
  if (clothing1 instanceof MensCloth)
Для этого вообщем то и создавались эти интерфейсы

**Comment by musicsupermax** [comment]
исправил
